.\" Manpage for py-completion-pyxbindman
.\"
.\" Copyright (C) 2013, Georgy Vlasov
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" man-db distribution.
.\"
.\" Contact wlasowegor@gmail.com to correct errors or typos.
.\"
.TH PY-COMPLETION-PYXBINDMAN 1 "30 May 2013" "1.0" "py-completion-pyxbindman man page"
.SH NAME
py-complation-pyxbindman \- a helper program that provides advanced completion
for pyxbindman
.SH DESCRIPTION
It is only intended to be used in the bash completion script.
.SH SEE ALSO
.BR pyxbindman (1)
.SH AUTHOR
Georgy Vlasov (wlasowegor@gmail.com, https://github.com/Suseika)
