.\" Manpage for pyxbindman
.\"
.\" Copyright (C) 2013, Georgy Vlasov
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" man-db distribution.
.\"
.\" Contact wlasowegor@gmail.com to correct errors or typos.
.\"
.TH PYXBINDMAN 1 "16 May 2013" "1.0" "pyxbindman man page"
.SH NAME
pyxbindman \- a command line tool for hotkeys management
.SH SYNOPSIS
.B pyxbindman
\fICOMMAND\fR [\fIKEYSYM\fR | \fIKEYCODE\fR] [\fB\-f\fR \fIFILE\fR]
.br
.B pyxbindman
\fB\-d\fR [\fIKEYSYM\fR | \fIKEYCODE\fR] [\fB\-f\fR \fIFILE\fR]
.br
.B pyxbindman
\fB\-D\fR \fICOMMAND\fR [\fB\-f\fR \fIFILE\fR]
.br
.br
.B pyxbindman [\fB\-l\fR \fIKEYSYM\fR | \fIKEYCODE\fR | \fICOMMAND\fR] [\fB\-f\fR \fIFILE\fR]
.br
.SH DESCRIPTION
.B pyxbindman
allows adding, removing and listing keyboard 
.IR bindings .
It works as a frontend to the 
.BR xbindkeys (1)
utility.  Its intention is to make binding keys as quick and simple as possible.
.BR pyxbindman 's 
key feature is smart completion of
commands, keysyms and keycodes. It is implied that the user is familiar with how 
.BR xbindkeys (1)
works.
.SH OPTIONS
.TP
\fB\-d\fR [\fIKEYSYM\fR | \fIKEYCODE\fR], \fB\-\-delete\fR [\fIKEYSYM\fR | \fIKEYCODE\fR] 
Deletes a binding by its \fIkeysym\fR or \fIkeycode\fR. If no
argument is provided, then it pops out a key-grabbind window and waits for a
combination to be pressed. When argument is provided, completion with Tab key
over all keys used in \fI.xbindkeysrc\fR file is available. To delete a binding
by its \fIkeycode\fR start the argument with \fBm\fR letter and press Tab (see
\fBxbindkeys\fR(1) for keycodes syntax).
.TP
\fB-D\fR \fICOMMAND\fR, \fB--delete-by-command\fR \fICOMMAND\fR 
Deletes a binding by its command. Completion with Tab key over all commands
defined in an \fI.xbindkeysrc\fR file is available.
.TP
\fB-s\fR [\fIKEYSYM\fR | \fIKEYCODE\fR | \fICOMMAND\fR], \fB--show\fR [\fIKEYSYM\fR | \fIKEYCODE\fR | \fICOMMAND\fR]
Searches for a particular binding in \fI.xbindkeysrc\fR by its command, keysym or keycode, and shows
it. When argument is provided, completion with Tab key over all keysyms and
commands used in \fI.xbindkeysrc\fR file is available. Otherwise a key-grabbing
window will appear.
.TP
\fB-f\fR \fIFILE\fR, \fB--file\fR \fIFILE\fR
Defines location of \fB.xbindkeysrc\fR file. Without this argument,
\fI$HOME/.xbindkeysrc\fR is used. If set, autocompletion will pick options from
that file.  If this argument presents, \fBxbindkeys\fR will not be restarted
after \fBpyxbindman\fR is called.
.TP
\fB-r\fR, \fB--restart\fR
Restarts
.B xbindkeys
daemon (or starts it, if it is not running). Other commands restart xbindkeys
automatically, so you usually don't need to call this command after changing
configuration with \fBpyxbindman\fR.
.TP
\fB-k\fR, \fB--kill\fR
Kills \fBxbindkeys\fR daemon.
.TP
\fB-h\fR, \fB--help\fR
Displays a brief description of options.
.SH FILES
.I ~/.xbindkeysrc
.RS
The default file where all the bindings are saved. See
.BR xbindkeys(1)
for further details.
.SH DIAGNOSTICS
.PP
.nf
\fBpyxbindman\fR returns error code when it can't find a command, keysym or
keycode in \fI.xbindkeysrc\fR with \fB\-d\fR and \fB\-D\fR options.
.PP
.nf
When \fBpyxbindman\fR is run with no X Window System available (for example,
from Linux console), it will return an error code if the action you are
attempting implies calling \fBxbindkeys -k\fR, which can only be run under X.
.SH EXAMPLES
It is recommended to always use double quotes for arguments containing spaces so
you won't need to see a lot of escaping with backslashes. However, quotes are
purely optional, and completion is available with or without them.
.PP
.nf
.RS
# Waits for a key combination and assigns "chromium" command to it
\fBpyxbindman chromium\fR

.PP
.nf
# Assigns another, more complicated command
\fBpyxbindman "gnome-terminal -e 'mc'"\fR

.PP
.nf
# Removes whatever is bound to Alt + F9 in ~/.xbindkeysrc and restarts xbindkeys
\fBpyxbindman -d "Alt + F9"\fR

.PP
.nf
# Removes a binding by its keycode (
\fBpyxbindman -d "m:0x40 + c:33"\fR

.PP
.nf
# Removes a binding that calls chromium command 
\fBpyxbindman -D chromium \fR

.PP
.nf
# Removes a binding that calls chromium command 
\fBpyxbindman -D chromium\fR
.SH SEE ALSO
.BR xbindkeys (1)
.SH AUTHOR
Georgy Vlasov (wlasowegor@gmail.com, https://github.com/Suseika)
